[build]
  command = "gunicorn -w 4 -b 0.0.0.0:5000 balance:app"
  publish = "static"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
