[build]
  command = "pip install beautifulsoup4 && pip install python balance.py"
  publish = "static"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
